export default {
  primary: '#9155FD',
  accent: '#0d6efd',
  secondary: '#8A8D93',
  success: '#56CA00',
  info: '#16B1FF',
  warning: '#FFB400',
  error: '#FF4C51',
  unionred : '#FFEBEE',
  unionpink : '#FCE4EC',
  unionpurple : '#F3E5F5',
  uniondeeppurple : '#EDE7F6',
  unionindigo : '#E8EAF6',
  unionblue : '#E3F2FD',
  unionlightblue : '#E1F5FE',
  unioncyan : '#E0F7FA',
  unionteal : '#E0F2F1',
  unionlightgreen : '#F1F8E9',
  uniongreen : '#E8F5E9',
  unionlime : '#F9FBE7',
  unionyellow : '#FFFDE7',
  unionamber : '#FFF8E1',
  unionorange : '#FFF3E0',
}
